kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-persistent-cfg
  namespace: kube-logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  #storageClassName: yourClass